---
version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      - image: garland/aws-cli-docker
    steps:
      - checkout
      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_TAG}" == /v[0-9]+\(\.[0-9]+\)*/ ]; then 
              aws s3 sync ~/circleci s3://watsonwoodwork.co.uk  --region eu-west-2 --delete
            fi
